# story_engine/config/templates.yml

template_1a:
  required_fields:
    - photo_1
    - model_name
    - sizes
  optional_fields: []
  description: "Single shoe image with brand text and sizes"

template_1b:
  required_fields:
    - photo_1
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Single shoe image with brand text and sizes"

template_1c:
  required_fields:
    - photo_1
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Single shoe image with brand text and sizes"

template_1d:
  required_fields:
    - photo_1
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Single shoe image with brand text and sizes"
  
template_1g:
  required_fields:
    - photo_1
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Single shoe image with brand text and sizes"

template_1hm:
  required_fields:
    - photo_1
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Single shoe image with brand text and sizes"
  
template_1rem:
  required_fields:
    - photo_1
  optional_fields: []
  description: "Single shoe image with brand text and sizes"
  
template_2a:
  required_fields:
    - photo_1
    - photo_2
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Two shoe images with brand name, model, and sizes"

template_2b:
  required_fields:
    - photo_1
    - photo_2
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Two shoe images with brand name, model, and sizes"

template_2np:
  required_fields:
    - photo_1
    - photo_2
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Two shoe images with brand name, model, and sizes"


template_2t:
  required_fields:
    - photo_1
    - photo_2
    - model_name
    - shop_name_en
    - sizes
    - brand
  optional_fields: 
    - logo
  description: "Two shoe images with brand name, model, and sizes"
