name: Story Generation

on:
  repository_dispatch:
    types: [storygen]

jobs:
  build-story:
    runs-on: ubuntu-latest

    steps:
      - name: Debug payload
        run: echo '${{ toJson(github.event.client_payload) }}'

      - name: Save order payload
        run: |
          mkdir -p orders/${{ github.event.client_payload.order_id }}
          echo '${{ toJson(github.event.client_payload) }}' \
            > orders/${{ github.event.client_payload.order_id }}/metadata.json
